<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QMAKQJB" failures="3" tests="20" name="com.vinGuru.tests.flightResevearion.FlightReseverationTest" time="27.752" errors="0" timestamp="2024-07-17T22:39:00 IST" skipped="0">
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightReseverationConfirmationTest" time="2.134"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="registartionConfirmationPage" time="1.259"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="userRegistaraionTest" time="1.318"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="registartionConfirmationPage" time="2.317"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightSelectionTest" time="0.989"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="userRegistaraionTest" time="1.683"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightReseverationConfirmationTest" time="1.355">
    <failure message="expected [$2338 USD] but found [$584 USD]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [$2338 USD] but found [$584 USD]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.vinGuru.tests.flightResevearion.FlightReseverationTest.flightReseverationConfirmationTest(FlightReseverationTest.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- flightReseverationConfirmationTest -->
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="registartionConfirmationPage" time="0.732"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightSearchTest" time="0.878"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="userRegistaraionTest" time="1.712"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightReseverationConfirmationTest" time="0.723">
    <failure message="expected [$1753 USD] but found [$584 USD]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [$1753 USD] but found [$584 USD]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.vinGuru.tests.flightResevearion.FlightReseverationTest.flightReseverationConfirmationTest(FlightReseverationTest.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- flightReseverationConfirmationTest -->
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightSearchTest" time="1.404"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightSelectionTest" time="2.076"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightSearchTest" time="1.129"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightSelectionTest" time="1.441"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="registartionConfirmationPage" time="1.267"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="userRegistaraionTest" time="1.641"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightSearchTest" time="1.527"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightSelectionTest" time="0.892"/>
  <system-out/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightReseverationConfirmationTest" time="1.275">
    <failure message="expected [$1169 USD] but found [$584 USD]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [$1169 USD] but found [$584 USD]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.vinGuru.tests.flightResevearion.FlightReseverationTest.flightReseverationConfirmationTest(FlightReseverationTest.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- flightReseverationConfirmationTest -->
  <system-out/>
</testsuite> <!-- com.vinGuru.tests.flightResevearion.FlightReseverationTest -->
